[server]
headless = true
address = "0.0.0.0"
port = 8501

[theme]
# Primary accent color for interactive elements
primaryColor = "#4257B2"

# Background color for the main content area
backgroundColor = "#1A1D28"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#262A38"

# Color used for almost all text
textColor = "#FFFFFF"

# Font family for all text in the app
font = "sans serif"